sudo: required
dist: trusty
python: "3.6"
services:
  - docker

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo -e "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_AUTH_TOKEN\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_AUTH_TOKEN" >> ~/.netrc
  - echo "Logging into the Heroku container!"
  - heroku container:login
  - sudo /etc/init.d/postgresql stop
  - docker-compose build
  - docker-compose run web bundle exec rake db:test:prepare

script:
  - docker-compose run --rm web bundle exec rake test

after_success:
  - heroku container:push web -a ${APP_NAME}

deploy:
  - provider: script
    script: bash docker_heroku_release
    on:
      branch: master
