language: ruby

rvm:
  - ruby-2.5.5

before_script:
  - bundle update --bundler
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - rake test

services:
  - postgresql

addons:
  postgresql: "9.4"
