language: ruby
rvm:
  - 2.5.5
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
script:
  - gem install bundler:1.17.3
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rails/test
